import re
from colorama import Fore, Back, Style, Cursor

from flask import Flask

from utils import *

import account, background, building, campaignV2, char, charBuild, charm, \
        crisis, deepsea, gacha, mail, online, tower, quest, pay, rlv2, shop, story, \
        user, asset.assetbundle, config.prod, social, templateShop, other, sandbox, charrotation, \
        activity, mission, depot
from admin import admin

import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

app = Flask(__name__)

import logging
logger = logging.getLogger('werkzeug')
logger.setLevel(logging.INFO)
logger.addFilter(lambda record: not re.match(r'.*(/syncPushMessage|/pb/async|/event|/batch_event|/deviceprofile/v4|/rqd/async).*', record.getMessage()))

app.add_url_rule("/activity/rewardAllMilestone", methods=["POST"], view_func=activity.ActivityMission.rewardAllMilestone)
app.add_url_rule("/activity/rewardMilestone", methods=["POST"], view_func=activity.ActivityMission.rewardMilestone)
app.add_url_rule("/activity/confirmActivityMission", methods=["POST"], view_func=activity.ActivityMission.confirmActivityMission)
app.add_url_rule("/activity/confirmActivityMissionList", methods=["POST"], view_func=activity.ActivityMission.confirmActivityMissionList)
app.add_url_rule("/activity/confirmActivityMissionGroup", methods=["POST"], view_func=activity.ActivityMission.confirmActivityMissionGroup)
app.add_url_rule("/activity/actCheckinAccess/getCheckInReward", methods=["POST"], view_func=activity.checkInReward.getCheckInReward)
app.add_url_rule("/activity/getActivityCheckInReward", methods=["POST"], view_func=activity.checkInReward.getActivityCheckInReward)
app.add_url_rule("/activity/prayOnly/getReward", methods=["POST"], view_func=activity.checkInReward.getReward)
app.add_url_rule("/activity/loginOnly/getReward", methods=["POST"], view_func=activity.checkInReward.getReward)
app.add_url_rule("/actcheckinvs/sign", methods=["POST"], view_func=activity.checkInReward.sign)
app.add_url_rule("/activity/loginOnlyUnique/getReward", methods=["POST"], view_func=activity.checkInReward.getReward)
app.add_url_rule("/activity/actBlessOnly/getCheckInReward", methods=["POST"], view_func=activity.checkInReward.getCheckInReward)
app.add_url_rule("/activity/actBlessOnly/changeFestivalChar", methods=["POST"], view_func=activity.checkInReward.changeFestivalChar)
app.add_url_rule("/activity/getSwitchOnlyReward", methods=["POST"], view_func=activity.switchOnly.getSwitchOnlyReward)
app.add_url_rule("/activity/teamQuest/refreshInfo", methods=["POST"], view_func=activity.multiplayer.refreshInfo)
app.add_url_rule("/invite/refreshInviteList", methods=["POST"], view_func=activity.multiplayer.refreshInviteList)
app.add_url_rule("/invite/switchInviteAccept", methods=["POST"], view_func=activity.multiplayer.switchInviteAccept)
app.add_url_rule("/invite/sendInvite", methods=["POST"], view_func=activity.multiplayer.sendInvite)
app.add_url_rule("/invite/processInvite", methods=["POST"], view_func=activity.multiplayer.processInvite)
app.add_url_rule("/activity/multiplayerV3/getInfo", methods=["POST"], view_func=activity.multiplayer.getInfo)
app.add_url_rule("/activity/multiplayerV3/changeTitle", methods=["POST"], view_func=activity.multiplayer.changeTitle)
app.add_url_rule("/activity/multiplayerV3/setBuff", methods=["POST"], view_func=activity.multiplayer.setBuff)
app.add_url_rule("/activity/multiplayerV3/setSquads", methods=["POST"], view_func=activity.multiplayer.setSquads)
app.add_url_rule("/activity/multiplayerV3/guideBattleStart", methods=["POST"], view_func=activity.multiplayer.guideBattleStart)
app.add_url_rule("/activity/multiplayerV3/guideBattleFinish", methods=["POST"], view_func=activity.multiplayer.guideBattleFinish)
app.add_url_rule("/activity/multiplayerV3/battleFinish", methods=["POST"], view_func=activity.multiplayer.battleFinish)
app.add_url_rule("/activity/multiplayerV3/battleStart", methods=["POST"], view_func=activity.multiplayer.battleStart)
app.add_url_rule("/activity/multiplayerV3/changePhoto", methods=["POST"], view_func=activity.multiplayer.changePhoto)
app.add_url_rule("/activity/multiplayerV3/commitAlbum", methods=["POST"], view_func=activity.multiplayer.multiplayer_commitAlbum)
app.add_url_rule("/activity/multiplayerV3/createTeam", methods=["POST"], view_func=activity.multiplayer.multiplayer_createTeam)
app.add_url_rule("/activity/multiplayerV3/joinTeam", methods=["POST"], view_func=activity.multiplayer.multiplayer_joinTeam)
app.add_url_rule("/activity/multiplayerV3/queryMatch", methods=["POST"], view_func=activity.multiplayer.multiplayer_queryMatch)
app.add_url_rule("/activity/multiplayerV3/report", methods=["POST"], view_func=activity.multiplayer.report)
app.add_url_rule("/activity/multiplayerV3/settleLike", methods=["POST"], view_func=activity.multiplayer.settleLike)
app.add_url_rule("/activity/multiplayerV3/startMatch", methods=["POST"], view_func=activity.multiplayer.multiplayer_startMatch)
app.add_url_rule("/activity/multiplayerV3/unlockBuff", methods=["POST"], view_func=activity.multiplayer.unlockBuff)
app.add_url_rule("/activity/enemyDuel/singleBattleStart", methods=["POST"], view_func=activity.enemyDuel.singleBattleStart)
app.add_url_rule("/activity/enemyDuel/singleBattleFinish", methods=["POST"], view_func=activity.enemyDuel.singleBattleFinish)
app.add_url_rule("/activity/enemyDuel/startMatch", methods=["POST"], view_func=activity.enemyDuel.enemyDuel_startMatch)
app.add_url_rule("/activity/enemyDuel/queryMatch", methods=["POST"], view_func=activity.enemyDuel.enemyDuel_queryMatch)
app.add_url_rule("/activity/enemyDuel/createTeam", methods=["POST"], view_func=activity.enemyDuel.enemyDuel_createTeam)
app.add_url_rule("/activity/enemyDuel/joinTeam", methods=["POST"], view_func=activity.enemyDuel.enemyDuel_joinTeam)
app.add_url_rule("/activity/enemyDuel/multiBattleFinish", methods=["POST"], view_func=activity.enemyDuel.enemyDuel_multiBattleFinish)
app.add_url_rule("/activity/enemyDuel/multiBattleStart", methods=["POST"], view_func=activity.enemyDuel.enemyDuel_multiBattleStart)
app.add_url_rule("/activity/act13side/clearFlag", methods=["POST"], view_func=activity.act13side.act13clearFlag)
app.add_url_rule("/activity/act13side/dailyMissionAccept", methods=["POST"], view_func=activity.act13side.act13dailyMissionAccept)
app.add_url_rule("/activity/act13side/dailyMissionCancel", methods=["POST"], view_func=activity.act13side.act13dailyMissionCancel)
app.add_url_rule("/activity/act13side/dailyMissionCommit", methods=["POST"], view_func=activity.act13side.act13dailyMissionCommit)
app.add_url_rule("/activity/act13side/dailyMissionRandom", methods=["POST"], view_func=activity.act13side.act13dailyMissionRandom)
app.add_url_rule("/activity/act13side/dailyMissionReplace", methods=["POST"], view_func=activity.act13side.act13dailyMissionReplace)
app.add_url_rule("/activity/act13side/longMissionCommit", methods=["POST"], view_func=activity.act13side.act13longMissionCommit)
app.add_url_rule("/activity/act13side/longMissionCommitBatch", methods=["POST"], view_func=activity.act13side.act13longMissionCommitBatch)
app.add_url_rule("/activity/typeAct20side/competitionFinish", methods=["POST"], view_func=activity.act20side.act20competitionFinish)
app.add_url_rule("/activity/typeAct20side/competitionStart", methods=["POST"], view_func=activity.act20side.act20competitionStart)
app.add_url_rule("/activity/typeAct20side/confirmExhiCar", methods=["POST"], view_func=activity.act20side.act20confirmExhiCar)
app.add_url_rule("/activity/typeAct20side/judge", methods=["POST"], view_func=activity.act20side.act20judge)
app.add_url_rule("/activity/typeAct20side/pick", methods=["POST"], view_func=activity.act20side.act20pick)
app.add_url_rule("/activity/typeAct20side/quickGetMilestoneAward", methods=["POST"], view_func=activity.act20side.act20quickGetMilestoneAward)
app.add_url_rule("/activity/typeAct20side/quickRecycle", methods=["POST"], view_func=activity.act20side.act20quickRecycle)
app.add_url_rule("/retro/typeAct20side/competitionStart", methods=["POST"], view_func=activity.act20side.act20retroCompetitionStart)
app.add_url_rule("/retro/typeAct20side/competitionFinish", methods=["POST"], view_func=activity.act20side.act20retroCompetitionFinish)
app.add_url_rule("/activity/act24side/alchemy", methods=["POST"], view_func=activity.act24side.act24alchemy)
app.add_url_rule("/activity/act24side/battleStart", methods=["POST"], view_func=quest.questBattleStart)
app.add_url_rule("/activity/act24side/battleFinish", methods=["POST"], view_func=quest.questBattleFinish)
app.add_url_rule("/activity/act24side/setTool", methods=["POST"], view_func=activity.act24side.act24setTool)
app.add_url_rule("/activity/act24side/eat", methods=["POST"], view_func=activity.act24side.act24eat)
app.add_url_rule("/activity/act24side/getHuntCollectRewards", methods=["POST"], view_func=activity.act24side.act24getHuntCollectRewards)
app.add_url_rule("/act25side/dailyRefresh", methods=["POST"], view_func=activity.act25side.dailyRefresh)
app.add_url_rule("/act25side/finishInvestigation", methods=["POST"], view_func=activity.act25side.finishInvestigation)
app.add_url_rule("/act25side/harvest", methods=["POST"], view_func=activity.act25side.act25harvest)
app.add_url_rule("/act25side/investigate", methods=["POST"], view_func=activity.act25side.investigate)
app.add_url_rule("/activity/act27side/inquirePurchase", methods=["POST"], view_func=activity.act27side.act27inquirePurchase)
app.add_url_rule("/activity/act27side/inquireSell", methods=["POST"], view_func=activity.act27side.act27inquireSell)
app.add_url_rule("/activity/act27side/nextDay", methods=["POST"], view_func=activity.act27side.act27nextDay)
app.add_url_rule("/activity/act27side/purchase", methods=["POST"], view_func=activity.act27side.act27purchase)
app.add_url_rule("/activity/act27side/saleSettle", methods=["POST"], view_func=activity.act27side.act27saleSettle)
app.add_url_rule("/activity/act27side/saleStart", methods=["POST"], view_func=activity.act27side.act27saleStart)
app.add_url_rule("/activity/act27side/sell", methods=["POST"], view_func=activity.act27side.act27sell)
app.add_url_rule("/act29side/commitMelody", methods=["POST"], view_func=activity.act29side.act29commitMelody)
app.add_url_rule("/act29side/startMajorInvest", methods=["POST"], view_func=activity.act29side.act29startMajorInvest)
app.add_url_rule("/act29side/syncthesize", methods=["POST"], view_func=activity.act29side.act29syncthesize)
app.add_url_rule("/activity/act35side/create", methods=["POST"], view_func=activity.act35side.act35create)
app.add_url_rule("/activity/act35side/settle", methods=["POST"], view_func=activity.act35side.act35settle)
app.add_url_rule("/activity/act35side/toBuy", methods=["POST"], view_func=activity.act35side.act35toBuy)
app.add_url_rule("/activity/act35side/refreshShop", methods=["POST"], view_func=activity.act35side.act35refreshShop)
app.add_url_rule("/activity/act35side/buySlot", methods=["POST"], view_func=activity.act35side.act35buySlot)
app.add_url_rule("/activity/act35side/buyCard", methods=["POST"], view_func=activity.act35side.act35buyCard)
app.add_url_rule("/activity/act35side/toProcess", methods=["POST"], view_func=activity.act35side.act35toProcess)
app.add_url_rule("/activity/act35side/process", methods=["POST"], view_func=activity.act35side.act35process)
app.add_url_rule("/activity/act35side/nextRound", methods=["POST"], view_func=activity.act35side.act35nextRound)
app.add_url_rule("/act36side/confirmDexNavReward", methods=["POST"], view_func=activity.act36side.act36confirmDexNavReward)
app.add_url_rule("/activity/act38side/completePuzzle", methods=["POST"], view_func=activity.act38side.act38completePuzzle)
app.add_url_rule("/activity/act38side/getInfo", methods=["POST"], view_func=activity.act38side.act38getInfo)
app.add_url_rule("/activity/act38side/useHint", methods=["POST"], view_func=activity.act38side.act38useHint)
app.add_url_rule("/activity/act42side/getDailyRewards", methods=["POST"], view_func=activity.act42side.act42getDailyRewards)
app.add_url_rule("/activity/act42side/acceptTask", methods=["POST"], view_func=activity.act42side.act42acceptTask)
app.add_url_rule("/activity/act42side/confirmTask", methods=["POST"], view_func=activity.act42side.act42confirmTask)
app.add_url_rule("/activity/act42side/getDailyTrustedItem", methods=["POST"], view_func=activity.act42side.act42getDailyTrustedItem)
app.add_url_rule("/activity/act42d0/battleFinish", methods=["POST"], view_func=activity.act42d0.act42d0_battleFinish)
app.add_url_rule("/activity/act42d0/battleStart", methods=["POST"], view_func=activity.act42d0.act42d0_battleStart)
app.add_url_rule("/activity/act42d0/challengeFinish", methods=["POST"], view_func=activity.act42d0.act42d0_challengeFinish)
app.add_url_rule("/activity/act42d0/challengeStart", methods=["POST"], view_func=activity.act42d0.act42d0_challengeStart)
app.add_url_rule("/activity/act42d0/recvMilestone", methods=["POST"], view_func=activity.act42d0.act42d0_recvMilestone)
app.add_url_rule("/activity/act44side/startGame", methods=["POST"], view_func=activity.act44game.act44startGame)
app.add_url_rule("/activity/act44side/nextState", methods=["POST"], view_func=activity.act44game.act44nextState)
app.add_url_rule("/activity/act44side/selectChoice", methods=["POST"], view_func=activity.act44game.act44SelectChoice)
app.add_url_rule("/activity/act44side/useInsight", methods=["POST"], view_func=activity.act44game.act44UseInsight)
app.add_url_rule("/activity/act45side/confirmChar", methods=["POST"], view_func=activity.act45side.act45confirmChar)
app.add_url_rule("/activity/act45side/confirmMail", methods=["POST"], view_func=activity.act45side.act45confirmMail)
app.add_url_rule("/activity/act46side/startGame", methods=["POST"], view_func=activity.act46side.act46startGame)
app.add_url_rule("/activity/act46side/settleGame", methods=["POST"], view_func=activity.act46side.act46settleGame)
app.add_url_rule("/activity/act46side/move", methods=["POST"], view_func=activity.act46side.act46move)
app.add_url_rule("/activity/act46side/endRound", methods=["POST"], view_func=activity.act46side.act46endRound)
app.add_url_rule("/activity/act46side/mining", methods=["POST"], view_func=activity.act46side.act46Mining)
app.add_url_rule("/activity/act1vhalfidle/unlockTech", methods=["POST"], view_func=activity.vhalfidle.unlockTech)
app.add_url_rule("/activity/act1vhalfidle/refreshProduct", methods=["POST"], view_func=activity.vhalfidle.refreshProduct)
app.add_url_rule("/activity/act1vhalfidle/harvest", methods=["POST"], view_func=activity.vhalfidle.harvest)
app.add_url_rule("/activity/act1vhalfidle/recruitNormal", methods=["POST"], view_func=activity.vhalfidle.recruitNormal)
app.add_url_rule("/activity/act1vhalfidle/recruitDirect", methods=["POST"], view_func=activity.vhalfidle.recruitDirect)
app.add_url_rule("/activity/act1vhalfidle/setAssistChar", methods=["POST"], view_func=activity.vhalfidle.setAssistChar)
app.add_url_rule("/activity/act1vhalfidle/battleStart", methods=["POST"], view_func=activity.vhalfidle.vhalfidlebattleStart)
app.add_url_rule("/activity/act1vhalfidle/battleFinish", methods=["POST"], view_func=activity.vhalfidle.vhalfidlebattleFinish)
app.add_url_rule("/activity/act1vhalfidle/replaceRate", methods=["POST"], view_func=activity.vhalfidle.replaceRate)
app.add_url_rule("/activity/act1vhalfidle/upgradeChar", methods=["POST"], view_func=activity.vhalfidle.vhalfidleUpgradeChar)
app.add_url_rule("/activity/act1vhalfidle/upgradeSkill", methods=["POST"], view_func=activity.vhalfidle.vhalfidleUpgradeSkill)
app.add_url_rule("/activity/act1vhalfidle/evolveChar", methods=["POST"], view_func=activity.vhalfidle.vhalfidleEvolveChar)
app.add_url_rule("/activity/autochessSeason/syncInfo", methods=["POST"], view_func=activity.autochessSeason.syncInfo)
app.add_url_rule("/activity/autochessSeason/setChessPoolDeploy", methods=["POST"], view_func=activity.autochessSeason.setChessPoolDeploy)
app.add_url_rule("/activity/autochessSeason/finishGuideBattle", methods=["POST"], view_func=activity.autochessSeason.autoChessFinishGuideBattle)
app.add_url_rule("/activity/autochessSeason/getFriendCharAssistList", methods=["POST"], view_func=activity.autochessSeason.autoChessGetFriendCharAssistList)
app.add_url_rule("/activity/autochessSeason/joinTeam", methods=["POST"], view_func=activity.autochessSeason.autoChessJoinTeam)
app.add_url_rule("/activity/autochessSeason/multiBattleFinish", methods=["POST"], view_func=activity.autochessSeason.autoChessMultiBattleFinish)
app.add_url_rule("/activity/autochessSeason/multiBattleStart", methods=["POST"], view_func=activity.autochessSeason.autoChessMultiBattleStart)
app.add_url_rule("/activity/autochessSeason/queryMatch", methods=["POST"], view_func=activity.autochessSeason.autoChessQueryMatch)
app.add_url_rule("/activity/autochessSeason/quitSingleGame", methods=["POST"], view_func=activity.autochessSeason.autoChessQuitSingleGame)
app.add_url_rule("/activity/autochessSeason/removeChessPoolChar", methods=["POST"], view_func=activity.autochessSeason.autoChessRemoveChessPoolChar)
app.add_url_rule("/activity/autochessSeason/report", methods=["POST"], view_func=activity.autochessSeason.autoChessReport)
app.add_url_rule("/activity/autochessSeason/setChessPoolAssist", methods=["POST"], view_func=activity.autochessSeason.autoChessSetChessPoolAssist)
app.add_url_rule("/activity/autochessSeason/setChessPoolDiyChar", methods=["POST"], view_func=activity.autochessSeason.autoChessSetChessPoolDiyChar)
app.add_url_rule("/activity/autochessSeason/settleGame", methods=["POST"], view_func=activity.autochessSeason.autoChessSettleGame)
app.add_url_rule("/activity/autochessSeason/settleLike", methods=["POST"], view_func=activity.autochessSeason.autoChessSettleLike)
app.add_url_rule("/activity/autochessSeason/startMatch", methods=["POST"], view_func=activity.autochessSeason.autoChessStartMatch)
app.add_url_rule("/autoChess/act1autochess", methods=["GET"], view_func=activity.autochessSeason.act2autochess)
app.add_url_rule("/autoChess/act2autochess" , methods=["GET"], view_func=activity.autochessSeason.act2autochess)
app.add_url_rule("/api/autoChess/act1autochess/playerSummary", methods=["GET"], view_func=activity.autochessSeason.act1playerSummary)
app.add_url_rule("/api/autoChess/act2autochess/playerSummary", methods=["GET"], view_func=activity.autochessSeason.act2playerSummary)
app.add_url_rule("/social/getFriendAndRequestSendList", methods=["POST"], view_func=activity.autochessSeason.getFriendAndRequestSendList)
app.add_url_rule("/activity/autochessSeason/createTeam", methods=["POST"], view_func=activity.autochessSeason.autoChessCreateTeam)
app.add_url_rule("/activity/autochessSeason/startGuideBattle", methods=["POST"], view_func=activity.autochessSeason.autoChessStartGuideBattle)
app.add_url_rule("/vecBreakV2/getSeasonRecord", methods=["POST"], view_func=activity.vecbreak.getSeasonRecord)
app.add_url_rule("/activity/vecBreakV2/changeBuffList", methods=["POST"], view_func=activity.vecbreak.vecV2changeBuffList)
app.add_url_rule("/activity/vecBreakV2/defendBattleStart", methods=["POST"], view_func=activity.vecbreak.defendBattleStart)
app.add_url_rule("/activity/vecBreakV2/defendBattleFinish", methods=["POST"], view_func=activity.vecbreak.defendBattleFinish)
app.add_url_rule("/activity/vecBreakV2/setDefend", methods=["POST"], view_func=activity.vecbreak.setDefend)
app.add_url_rule("/activity/vecBreakV2/battleStart", methods=["POST"], view_func=activity.vecbreak.vecV2BattleStart)
app.add_url_rule("/activity/vecBreakV2/battleFinish", methods=["POST"], view_func=activity.vecbreak.vecV2battleFinish)
app.add_url_rule("/activity/arcade/battleStart", methods=["POST"], view_func=activity.arcade.arcadeBattleStart)
app.add_url_rule("/activity/arcade/battleFinish", methods=["POST"], view_func=activity.arcade.arcadeBattleFinish)
app.add_url_rule("/activity/football/battleStart", methods=["POST"], view_func=activity.football.footballBattleStart)
app.add_url_rule("/activity/football/battleFinish", methods=["POST"], view_func=activity.football.footballBattleFinish)
app.add_url_rule("/activity/interlock/milestone", methods=["POST"], view_func=activity.interlock.interlock_milestone)
app.add_url_rule("/activity/interlock/milestoneBatch", methods=["POST"], view_func=activity.interlock.interlock_milestoneBatch)
app.add_url_rule("/activity/interlock/setDefend", methods=["POST"], view_func=activity.interlock.interlock_setDefend)
app.add_url_rule("/activity/interlock/setSquad", methods=["POST"], view_func=activity.interlock.interlock_setSquad)
app.add_url_rule("/activity/exchangeActivityShopItem", methods=["POST"], view_func=activity.exchangeActivityShopItem)
app.add_url_rule("/activity/getActivityCollectionReward", methods=["POST"], view_func=activity.getActivityCollectionReward)
app.add_url_rule("/activity/getActivityShopInfo", methods=["POST"], view_func=activity.getActivityShopInfo)
app.add_url_rule("/activity/recycleCharms", methods=["POST"], view_func=activity.recycleCharms)
app.add_url_rule("/activity/roguelike/createGame", methods=["POST"], view_func=activity.roguelike.roguelike_createGame)
app.add_url_rule("/activity/roguelike/finishGame", methods=["POST"], view_func=activity.roguelike.roguelike_finishGame)
app.add_url_rule("/activity/roguelike/giveUpGame", methods=["POST"], view_func=activity.roguelike.roguelike_giveUpGame)
app.add_url_rule("/activity/roguelike/milestoneReward", methods=["POST"], view_func=activity.roguelike.roguelike_milestoneReward)
app.add_url_rule("/activity/roguelike/milestoneRewardTryBest", methods=["POST"], view_func=activity.roguelike.roguelike_milestoneRewardTryBest)
app.add_url_rule("/activity/roguelike/upgradeOutBuff", methods=["POST"], view_func=activity.roguelike.roguelike_upgradeOutBuff)
app.add_url_rule("/activity/tryGetCharmFirstReward", methods=["POST"], view_func=activity.tryGetCharmFirstReward)
app.add_url_rule("/activity/typeAct3d0/gacha", methods=["POST"], view_func=activity.act3d0.act3d0_gacha)
app.add_url_rule("/activity/typeAct3d0/getGachaInfo", methods=["POST"], view_func=activity.act3d0.act3d0_getGachaInfo)
app.add_url_rule("/activity/typeAct3d0/getMilestoneReward", methods=["POST"], view_func=activity.act3d0.act3d0_getMilestoneReward)
app.add_url_rule("/activity/typeAct3d0/selectFaction", methods=["POST"], view_func=activity.act3d0.act3d0_selectFaction)
app.add_url_rule("/activity/typeAct4d0/finishStory", methods=["POST"], view_func=activity.act4d0.act4d0_finishStory)
app.add_url_rule("/activity/typeAct4d0/getReward", methods=["POST"], view_func=activity.act4d0.act4d0_getReward)
app.add_url_rule("/activity/typeAct4d0/unlockStory", methods=["POST"], view_func=activity.act4d0.act4d0_unlockStory)
app.add_url_rule("/activity/typeAct5d0/getReward", methods=["POST"], view_func=activity.act5d0.act5d0_getReward)
app.add_url_rule("/activity/typeAct5d1/buyGoods", methods=["POST"], view_func=activity.act5d1.act5d1_buyGoods)
app.add_url_rule("/activity/typeAct5d1/buyRune", methods=["POST"], view_func=activity.act5d1.act5d1_buyRune)
app.add_url_rule("/activity/typeAct5d1/getGoodsList", methods=["POST"], view_func=activity.act5d1.act5d1_getGoodsList)
app.add_url_rule("/activity/typeAct5d1/getInfo", methods=["POST"], view_func=activity.act5d1.act5d1_getInfo)
app.add_url_rule("/activity/typeAct9d0/readNews", methods=["POST"], view_func=activity.act9d0.act9d0_readNews)
app.add_url_rule("/activity/year5General/getInfReward", methods=["POST"], view_func=activity.year5General.year5General_getInfReward)

app.add_url_rule("/app/getSettings", methods=["POST"], view_func=user.appGetSettings)
app.add_url_rule("/app/getCode", methods=["POST"], view_func=user.appGetCode)

app.add_url_rule("/account/login", methods=["POST"], view_func=account.accountLogin)
app.add_url_rule("/account/syncData", methods=["POST"], view_func=account.SyncData)
app.add_url_rule("/account/syncStatus", methods=["POST"], view_func=account.SyncStatus)
app.add_url_rule("/account/yostar_auth_request", methods=["POST"], view_func=account.accountYostarAuthRequest)
app.add_url_rule("/account/yostar_auth_submit", methods=["POST"], view_func=account.accountYostarAuthSubmit)
app.add_url_rule("/account/syncPushMessage", methods=["POST"], view_func=account.syncPushMessage)

app.add_url_rule("/assetbundle/official/<string:system>/assets/<string:assetsHash>/<path:fileName>", methods = ["GET"], view_func=asset.assetbundle.getFile)
app.add_url_rule("/official/<string:system>/assets/<string:assetsHash>/<path:fileName>", methods=["GET"], view_func=asset.assetbundle.getFile)
app.add_url_rule("/arknights/<path:subpath>", methods=["GET"], view_func=asset.assetbundle.proxy_assest)


app.add_url_rule("/background/setBackground", methods=["POST"], view_func=background.SetBackground)
app.add_url_rule("/homeTheme/change", methods=["POST"], view_func=background.homeThemeChange)

app.add_url_rule("/building/sync", methods=["POST"], view_func=building.Sync)
app.add_url_rule("/building/getRecentVisitors", methods=["POST"], view_func=building.GetRecentVisitors)
app.add_url_rule("/building/getInfoShareVisitorsNum", methods=["POST"], view_func=building.GetInfoShareVisitorsNum)
app.add_url_rule("/building/assignChar", methods=["POST"], view_func=building.AssignChar)
app.add_url_rule("/building/changeDiySolution", methods=["POST"], view_func=building.ChangeDiySolution)
app.add_url_rule("/building/changeManufactureSolution", methods=["POST"], view_func=building.ChangeManufactureSolution)
app.add_url_rule("/building/settleManufacture", methods=["POST"], view_func=building.SettleManufacture)
app.add_url_rule("/building/workshopSynthesis", methods=["POST"], view_func=building.WorkshopSynthesis)
app.add_url_rule("/building/upgradeSpecialization", methods=["POST"], view_func=building.UpgradeSpecialization)
app.add_url_rule("/building/completeUpgradeSpecialization", methods=["POST"], view_func=building.CompleteUpgradeSpecialization)
app.add_url_rule("/building/deliveryOrder", methods=["POST"], view_func=building.DeliveryOrder)
app.add_url_rule("/building/deliveryBatchOrder",methods=["POST"], view_func=building.DeliveryBatchOrder)
app.add_url_rule("/building/cleanRoomSlot", methods=["POST"], view_func=building.CleanRoomSlot)
app.add_url_rule("/building/getAssistReport", methods=["POST"], view_func=building.getAssistReport)
app.add_url_rule("/building/setBuildingAssist", methods=["POST"], view_func=building.setBuildingAssist)
app.add_url_rule("/building/degradeRoom", methods=["POST"], view_func=building.changRoomLevel)
app.add_url_rule("/building/upgradeRoom", methods=["POST"], view_func=building.changRoomLevel)
app.add_url_rule("/building/changeStrategy", methods=["POST"], view_func=building.changeStrategy)
app.add_url_rule("/building/addPresetQueue", methods=["POST"], view_func=building.addPresetQueue)
app.add_url_rule("/building/deletePresetQueue", methods=["POST"], view_func=building.deletePresetQueue)
app.add_url_rule("/building/editPresetQueue", methods=["POST"], view_func=building.editPresetQueue)
app.add_url_rule("/building/usePresetQueue", methods=["POST"], view_func=building.usePresetQueue)
app.add_url_rule("/building/editLockQueue", methods=["POST"], view_func=building.editLockQueue)
app.add_url_rule("/building/batchRestChar", methods=["POST"], view_func=building.batchRestChar)
app.add_url_rule("/building/buildRoom", methods=["POST"], view_func=building.buildRoom)
app.add_url_rule("/building/getClueBox", methods=["POST"], view_func=building.getClueBox)
app.add_url_rule("/building/getClueFriendList", methods=["POST"], view_func=building.getClueFriendList)
app.add_url_rule("/building/changeBGM", methods=["POST"], view_func=building.changeBGM)
app.add_url_rule("/building/setPrivateDormOwner", methods=["POST"], view_func=building.setPrivateDormOwner)
app.add_url_rule('/building/confirmPrivateDormIntimacy', methods=['POST'], view_func=building.confirmPrivateDormIntimacy)
app.add_url_rule("/building/gainIntimacy", methods=["POST"], view_func=building.gainIntimacy)
app.add_url_rule("/building/gainAssistIntimacy", methods=["POST"], view_func=building.gainAssistIntimacy)
app.add_url_rule("/building/gainAllIntimacy", methods=["POST"], view_func=building.gainAllIntimacy)
app.add_url_rule("/building/visitBuilding", methods=["POST"], view_func=building.visitBuilding)
app.add_url_rule("/building/completeUpgradeRoom", methods=["POST"], view_func=building.completeUpgradeRoom)
app.add_url_rule("/building/changeSaleSolution", methods=["POST"], view_func=building.changeSaleSolution)
app.add_url_rule("/building/settleSale", methods=["POST"], view_func=building.settleSale)
app.add_url_rule("/building/upgradeDiyLevel", methods=["POST"], view_func=building.upgradeDiyLevel)
app.add_url_rule("/building/saveDiyPresetSolution", methods=["POST"], view_func=building.saveDiyPresetSolution)
app.add_url_rule("/building/changePresetName", methods=["POST"], view_func=building.changePresetName)
app.add_url_rule("/building/getThumbnailUrl", methods=["POST"], view_func=building.getThumbnailUrl)
app.add_url_rule("/building/workshopDecomposition", methods=["POST"], view_func=building.workshopDecomposition)
app.add_url_rule("/building/deleteOrder", methods=["POST"], view_func=building.deleteOrder)
app.add_url_rule("/building/accelerateOrder", methods=["POST"], view_func=building.accelerateOrder)
app.add_url_rule("/building/accelerateSolution", methods=["POST"], view_func=building.accelerateSolution)
app.add_url_rule("/building/buyLabor", methods=["POST"], view_func=building.buyLabor)
app.add_url_rule("/building/deleteOwnClue", methods=["POST"], view_func=building.deleteOwnClue)
app.add_url_rule("/building/deleteReceiveClue", methods=["POST"], view_func=building.deleteReceiveClue)
app.add_url_rule("/building/putClueToTheBoard", methods=["POST"], view_func=building.putClueToTheBoard)
app.add_url_rule("/building/putClueToTheBoardAuto", methods=["POST"], view_func=building.putClueToTheBoardAuto)
app.add_url_rule("/building/sendClueAuto", methods=["POST"], view_func=building.sendClueAuto)
app.add_url_rule("/building/sendClue", methods=["POST"], view_func=building.sendClue)
app.add_url_rule("/building/getMeetingroomReward", methods=["POST"], view_func=building.getMeetingroomReward)
app.add_url_rule("/building/receiveClueToStock", methods=["POST"], view_func=building.receiveClueToStock)
app.add_url_rule("/building/startInfoShare", methods=["POST"], view_func=building.startInfoShare)
app.add_url_rule("/building/getDailyClue", methods=["POST"], view_func=building.getDailyClue)
app.add_url_rule("/building/getOthersMessageBoardContent", methods=["POST"], view_func=building.getOthersMessageBoardContent)
app.add_url_rule("/building/confirmMessageBoardReward", methods=["POST"], view_func=building.confirmMessageBoardReward)
app.add_url_rule("/building/sendEmoji", methods=["POST"], view_func=building.sendEmoji)
app.add_url_rule("/building/batchChangeWorkChar", methods=["POST"], view_func=building.batchChangeWorkChar)
app.add_url_rule("/building/useOnePresetQueue", methods=["POST"], view_func=building.useOnePresetQueue)

app.add_url_rule("/campaignV2/battleStart", methods=["POST"], view_func=campaignV2.campaignV2BattleStart)
app.add_url_rule("/campaignV2/battleFinish", methods=["POST"], view_func=campaignV2.campaignV2BattleFinish)
app.add_url_rule("/campaignV2/battleSweep", methods=["POST"], view_func=campaignV2.campaignV2BattleSweep)
app.add_url_rule("/campaignV2/getBreakReward", methods=["POST"], view_func=campaignV2.getBreakReward)
app.add_url_rule("/campaignV2/getExMissionReward", methods=["POST"], view_func=campaignV2.getExMissionReward)

app.add_url_rule("/char/changeMarkStar", methods=["POST"], view_func=char.charChangeMarkStar)

app.add_url_rule("/charBuild/addonStage/battleStart", methods=["POST"], view_func=quest.questBattleStart)
app.add_url_rule("/charBuild/addonStage/battleFinish", methods=["POST"], view_func=quest.questBattleFinish)
app.add_url_rule("/charBuild/addonStory/unlock", methods=["POST"], view_func=charBuild.charBuildaddonStoryUnlock)
app.add_url_rule("/charBuild/batchSetCharVoiceLan", methods=["POST"], view_func=charBuild.charBuildBatchSetCharVoiceLan)
app.add_url_rule("/charBuild/setCharVoiceLan", methods=["POST"], view_func=charBuild.charBuildSetCharVoiceLan)
app.add_url_rule("/charBuild/setDefaultSkill", methods=["POST"], view_func=charBuild.charBuildSetDefaultSkill)
app.add_url_rule("/charBuild/changeCharSkin", methods=["POST"], view_func=charBuild.charBuildChangeCharSkin)
app.add_url_rule("/charBuild/setEquipment", methods=["POST"], view_func=charBuild.charBuildSetEquipment)
app.add_url_rule("/charBuild/changeCharTemplate", methods=["POST"], view_func=charBuild.charBuildChangeCharTemplate)
app.add_url_rule("/charBuild/upgradeChar", methods=["POST"], view_func=charBuild.upgradeChar)
app.add_url_rule("/charBuild/evolveChar", methods=["POST"], view_func=charBuild.evolveChar)
app.add_url_rule("/charBuild/lockChar", methods=["POST"], view_func=charBuild.lockChar)
app.add_url_rule("/charBuild/sellChar", methods=["POST"], view_func=charBuild.sellChar)
app.add_url_rule("/charBuild/boostPotential", methods=["POST"], view_func=charBuild.boostPotential)
app.add_url_rule("/charBuild/upgradeSkill", methods=["POST"], view_func=charBuild.upgradeSkill)
app.add_url_rule("/charBuild/upgradeSpecialization", methods=["POST"], view_func=charBuild.upgradeSpecialization)
app.add_url_rule("/charBuild/completeUpgradeSpecialization", methods=["POST"], view_func=charBuild.completeUpgradeSpecialization)
app.add_url_rule("/charBuild/evolveCharUseItem", methods=["POST"], view_func=charBuild.evolveCharUseItem)
app.add_url_rule("/charBuild/upgradeCharLevelMaxUseItem", methods=["POST"], view_func=charBuild.upgradeCharLevelMaxUseItem)
app.add_url_rule("/charBuild/upgradeSpecializedSkillUseItem", methods=["POST"], view_func=charBuild.upgradeSpecializedSkillUseItem)
app.add_url_rule("/charBuild/unlockEquipment", methods=["POST"], view_func=charBuild.unlockEquipment)
app.add_url_rule("/charBuild/upgradeEquipment", methods=["POST"], view_func=charBuild.upgradeEquipment)
app.add_url_rule("/charBuild/getSpCharMissionReward", methods=["POST"], view_func=charBuild.getSpCharMissionReward)

app.add_url_rule("/charm/setSquad", methods=["POST"], view_func=charm.charmSetSquad)

app.add_url_rule("/", methods=["GET"], view_func=config.prod.redirect_rote)
app.add_url_rule("/config/prod/announce_meta/Android/preannouncement.meta.json", methods = ["GET"], view_func=config.prod.prodPreAnnouncement)
app.add_url_rule("/config/prod/announce_meta/Android/announcement.meta.json", methods = ["GET"], view_func=config.prod.prodAnnouncement)
app.add_url_rule("/api/remote_config/1/prod/default/Android/remote_config", methods=["GET"], view_func=config.prod.prodRemoteConfig)
app.add_url_rule("/api/remote_config/1/prod/default/Windows/remote_config", methods=["GET"], view_func=config.prod.prodRemoteConfig)
app.add_url_rule("/config/prod/official/Android/version", methods = ["GET"], view_func=config.prod.prodAndroidVersion)
app.add_url_rule("/config/prod/official/Windows/version", methods=["GET"], view_func=config.prod.prodWindowsVersion)
app.add_url_rule("/config/prod/official/network_config", methods=["GET"], view_func=config.prod.prodNetworkConfig)
app.add_url_rule("/config/prod/b/network_config", methods=["GET"], view_func=config.prod.prodNetworkConfig)
app.add_url_rule("/api/remote_config/1/prod/default/Android/network_config", methods=["GET"], view_func=config.prod.prodNetworkConfig_new)
app.add_url_rule("/api/remote_config/1/prod/default/Windows/network_config", methods=["GET"], view_func=config.prod.prodNetworkConfig_new)
app.add_url_rule("/api/remote_config/1/prod/bilibili/Windows/network_config", methods=["GET"], view_func=config.prod.prodNetworkConfig)
app.add_url_rule("/audit/official/Windows/<path:subpath>", methods=["GET"], view_func=config.prod.prodAudit)
app.add_url_rule("/audit/official/Android/version_<path:subpath>", methods=["GET"], view_func=config.prod.prodAndroidVersion)
app.add_url_rule("/audit/official/<string:system>/assets/<string:assetsHash>/<path:fileName>", methods=["GET"], view_func=asset.assetbundle.getFile)
app.add_url_rule("/config/prod/official/refresh_config", methods = ["GET"], view_func=config.prod.prodRefreshConfig)
app.add_url_rule("/config/prod/official/remote_config", methods = ["GET"], view_func=config.prod.prodRemoteConfig)
app.add_url_rule("/api/game/get_latest", methods=["GET"], view_func=config.prod.get_latest)
app.add_url_rule("/api/game/get_latest_game_info", methods = ["GET"], view_func= config.prod.get_latest_game_info)
app.add_url_rule("/api/gate/meta/Android", methods = ["GET"], view_func= config.prod.prodGateMeta)
app.add_url_rule("/api/gate/meta/Windows", methods = ["GET"], view_func= config.prod.prodGateMeta)
app.add_url_rule("/api/remote_config/101/prod/default/Android/ak_sdk_config", methods = ["GET"], view_func= config.prod.ak_sdk_config)
app.add_url_rule("/api/remote_config/101/prod/default/Windows/ak_sdk_config", methods = ["GET"], view_func= config.prod.ak_sdk_config)
app.add_url_rule("/gameBulletin", methods=["GET"], view_func= config.prod.prodGameBulletin)
app.add_url_rule("/analytics/collect", methods=["POST"], view_func= config.prod.prodAnalyticsCollect)
app.add_url_rule("/api/game/<path:subpath>", methods=["GET"], view_func= config.prod.prodBulletinList)
app.add_url_rule("/announce/images/<path:subpath>", methods=["GET"], view_func= config.prod.announceImages)

app.add_url_rule("/crisis/getInfo", methods=["POST"], view_func=crisis.crisisGetCrisisInfo)
app.add_url_rule("/crisis/battleStart", methods=["POST"], view_func=crisis.crisisBattleStart)
app.add_url_rule("/crisis/battleFinish", methods=["POST"], view_func=crisis.crisisBattleFinish)
app.add_url_rule("/crisisV2/getInfo", methods=["POST"], view_func=crisis.crisisV2_getInfo)
app.add_url_rule("/crisisV2/confirmMissions", methods=["POST"], view_func=crisis.crisisV2_confirmMissions)
app.add_url_rule("/crisisV2/battleStart", methods=["POST"], view_func=crisis.crisisV2_battleStart)
app.add_url_rule("/crisisV2/battleFinish", methods=["POST"], view_func=crisis.crisisV2_battleFinish)
app.add_url_rule("/crisisV2/getSnapshot", methods=["POST"], view_func=crisis.crisisV2_getSnapshot)
app.add_url_rule("/crisisV2/getGoodList", methods=["POST"], view_func=crisis.crisisV2_getGoodList)

app.add_url_rule("/deepSea/branch", methods=["POST"], view_func=deepsea.deepSeaBranch)
app.add_url_rule("/deepSea/event", methods=["POST"], view_func=deepsea.deepSeaEvent)

app.add_url_rule("/mail/getMetaInfoList", methods=["POST"], view_func=mail.mailGetMetaInfoList)
app.add_url_rule("/mail/listMailBox", methods=["POST"], view_func=mail.mailListMailBox)
app.add_url_rule("/mailCollection/getList", methods=["POST"], view_func=mail.mailCollectionGetList)
app.add_url_rule("/mail/receiveMail", methods=["POST"], view_func=mail.mailReceiveMail)
app.add_url_rule("/mail/receiveAllMail", methods=["POST"], view_func=mail.mailReceiveAllMail)
app.add_url_rule("/mail/removeAllReceivedMail", methods=["POST"], view_func=mail.mailRemoveAllReceivedMail)

app.add_url_rule("/online/v1/ping", methods=["POST"], view_func=online.onlineV1Ping)
app.add_url_rule("/online/v1/loginout", methods=["POST"], view_func=online.onlineV1LoginOut)
app.add_url_rule("/user/online/v1/loginout", methods=["POST"], view_func=online.onlineV1LoginOut)

app.add_url_rule("/tower/createGame", methods=["POST"], view_func=tower.towerCreateGame)
app.add_url_rule("/tower/initGodCard", methods=["POST"], view_func=tower.towerInitGodCard)
app.add_url_rule("/tower/initGame", methods=["POST"], view_func=tower.towerInitGame)
app.add_url_rule("/tower/initCard", methods=["POST"], view_func=tower.towerInitCard)
app.add_url_rule("/tower/battleStart", methods=["POST"], view_func=tower.towerBattleStart)
app.add_url_rule("/tower/battleFinish", methods=["POST"], view_func=tower.towerBattleFinish)
app.add_url_rule("/tower/recruit", methods=["POST"], view_func=tower.towerRecruit)
app.add_url_rule("/tower/chooseSubGodCard", methods=["POST"], view_func=tower.towerChooseSubGodCard)
app.add_url_rule("/tower/settleGame", methods=["POST"], view_func=tower.towerSettleGame)
app.add_url_rule("/tower/layerReward", methods=["POST"], view_func=tower.layerReward)
app.add_url_rule("/tower/seasonMissonsAward", methods=["POST"], view_func=tower.seasonMissonsAward)
app.add_url_rule("/tower/sweepGame", methods=["POST"], view_func=tower.sweepGame)

app.add_url_rule("/pay/getUnconfirmedOrderIdList", methods=["POST"], view_func=pay.GetUnconfirmedOrderIdList)
app.add_url_rule("/u8/pay/getAllProductList", methods=["POST"], view_func=pay.getAllProductList)
app.add_url_rule("/pay/createOrder", methods=["POST"], view_func=pay.getcreateOrder)
app.add_url_rule("/pay/v1/query_show_app_product", methods=["POST"], view_func=pay.queryshowappproduct)
app.add_url_rule("/user/pay/v1/query_payment_config", methods=["GET"], view_func=pay.querypaymentconfig)
app.add_url_rule("/user/pay/order/v2/create/app_product", methods=["POST"], view_func=pay.createappproduct)
app.add_url_rule("/user/pay/order/v1/create/app_product/alipay", methods=["POST"], view_func=pay.alipay)
app.add_url_rule("/user/pay/order/v1/create/app_product/wechat", methods=["POST"], view_func=pay.wechat)
app.add_url_rule("/pay/order/v1/check", methods=["POST"], view_func=pay.check)
app.add_url_rule("/pay/order/v1/state", methods=["GET"], view_func=pay.state)
app.add_url_rule("/pay/confirmOrder", methods=["POST"], view_func=pay.confirmOrder)
app.add_url_rule("/pay/createOrderAppstore", methods=["POST"], view_func=pay.createOrderAppstore)
app.add_url_rule("/pay/confirmOrderAppstore", methods=["POST"], view_func=pay.confirmOrderAppstore)
app.add_url_rule("/pay/confirmOrderAppstoreNew", methods=["POST"], view_func=pay.confirmOrderAppstoreNew)

app.add_url_rule("/quest/battleStart", methods=["POST"], view_func=quest.questBattleStart)
app.add_url_rule("/quest/battleFinish", methods=["POST"], view_func=quest.questBattleFinish)
app.add_url_rule("/quest/saveBattleReplay", methods=["POST"], view_func=quest.questSaveBattleReplay)
app.add_url_rule("/quest/getBattleReplay", methods=["POST"], view_func=quest.questGetBattleReplay)
app.add_url_rule("/quest/changeSquadName", methods=["POST"], view_func=quest.questChangeSquadName)
app.add_url_rule("/quest/squadFormation", methods=["POST"], view_func=quest.questSquadFormation)
app.add_url_rule("/quest/getAssistList", methods=["POST"], view_func=quest.questGetAssistList)
app.add_url_rule("/quest/battleContinue", methods=["POST"], view_func=quest.questBattleContinue)
app.add_url_rule("/storyreview/markStoryAcceKnown", methods=["POST"], view_func=quest.markStoryAcceKnown)
app.add_url_rule("/storyreview/readStory", methods=["POST"], view_func=quest.readStory)
app.add_url_rule("/car/confirmBattleCar", methods=["POST"], view_func=quest.confirmBattleCar)
app.add_url_rule("/templateTrap/setTrapSquad", methods=["POST"], view_func=quest.setTrapSquad)
app.add_url_rule("/act25side/battleStart", methods=["POST"], view_func=quest.questBattleStart)
app.add_url_rule("/act25side/battleFinish", methods=["POST"], view_func=quest.questBattleFinish)
app.add_url_rule("/quest/unlockStageFog", methods=["POST"], view_func=quest.unlockStageFog)
app.add_url_rule("/quest/unlockHideStage", methods=["POST"], view_func=quest.unlockHideStage)
app.add_url_rule("/quest/getCowLevelReward", methods=["POST"], view_func=quest.getCowLevelReward)
app.add_url_rule("/quest/getMainlineRecordRewards", methods=["POST"], view_func=quest.getMainlineRecordRewards)
app.add_url_rule("/quest/getMainlineCache", methods=["POST"], view_func=quest.getMainlineCache)
app.add_url_rule("/retro/unlockRetroBlock", methods=["POST"], view_func=quest.unlockRetroBlock)
app.add_url_rule("/retro/getRetroTrailReward", methods=["POST"], view_func=quest.getRetroTrailReward)
app.add_url_rule("/retro/getRetroPassReward", methods=["POST"], view_func=quest.getRetroPassReward)
app.add_url_rule("/rune/battleStart", methods=["POST"], view_func=quest.runeBattleStart)
app.add_url_rule("/rune/battleFinish", methods=["POST"], view_func=quest.runeBattleFinish)
app.add_url_rule("/storyreview/unlockStoryByCoin", methods=["POST"], view_func=quest.unlockStoryByCoin)
app.add_url_rule("/storyreview/rewardGroup", methods=["POST"], view_func=quest.rewardGroup)
app.add_url_rule("/storyreview/trailReward", methods=["POST"], view_func=quest.trailReward)
app.add_url_rule("/trainingGround/battleStart", methods=["POST"], view_func=quest.trainingGroundBattleStart)
app.add_url_rule("/trainingGround/battleFinish", methods=["POST"], view_func=quest.trainingGroundBattleFinish)

app.add_url_rule("/mission/confirmMission", methods=["POST"], view_func=mission.mission_manger().ConfirmMission)
app.add_url_rule("/mission/autoConfirmMissions", methods=["POST"], view_func=mission.mission_manger().AutoConfirmMissions)
app.add_url_rule("/mission/exchangeMissionRewards", methods=["POST"], view_func=mission.exchangeMissionRewards)
app.add_url_rule("/mission/confirmMissionList", methods=["POST"], view_func=mission.confirmMissionList)
app.add_url_rule("/mission/confirmMissionGroup", methods=["POST"], view_func=mission.confirmMissionGroup)
app.add_url_rule("/mission/confirmMultiGroupMissionList", methods=["POST"], view_func=mission.confirmMultiGroupMissionList)

app.add_url_rule("/activity/bossRush/battleStart", methods=["POST"], view_func=quest.questBattleStart)
app.add_url_rule("/activity/bossRush/battleFinish", methods=["POST"], view_func=quest.questBattleFinish)
app.add_url_rule("/activity/bossRush/relicSelect", methods=["POST"], view_func=quest.relicSelect)

app.add_url_rule("/aprilFool/act7fun/battleStart", methods=["POST"], view_func=quest.questBattleStart)
app.add_url_rule("/aprilFool/act7fun/battleFinish", methods=["POST"], view_func=quest.act7fun_questBattleFinish)
app.add_url_rule("/aprilFool/act6fun/battleStart", methods=["POST"], view_func=quest.questBattleStart)
app.add_url_rule("/aprilFool/act6fun/battleFinish", methods=["POST"], view_func=quest.act6fun_questBattleFinish)
app.add_url_rule("/aprilFool/act5fun/battleStart", methods=["POST"], view_func=quest.questBattleStart)
app.add_url_rule("/aprilFool/act5fun/battleFinish", methods=["POST"], view_func=quest.act5fun_questBattleFinish)
app.add_url_rule("/aprilFool/act4fun/battleStart", methods=["POST"], view_func=quest.questBattleStart)
app.add_url_rule("/aprilFool/act4fun/battleFinish", methods=["POST"], view_func=quest.act4fun_questBattleFinish)
app.add_url_rule("/aprilFool/act4fun/liveSettle", methods=["POST"], view_func=quest.act4fun_liveSettle)
app.add_url_rule("/aprilFool/act3fun/battleStart", methods=["POST"], view_func=quest.questBattleStart)
app.add_url_rule("/aprilFool/act3fun/battleFinish", methods=["POST"], view_func=quest.questBattleFinish)

app.add_url_rule("/rlv2/giveUpGame", methods=["POST"], view_func=rlv2.rlv2GiveUpGame)
app.add_url_rule("/rlv2/createGame", methods=["POST"], view_func=rlv2.rlv2CreateGame)
app.add_url_rule("/rlv2/chooseInitialRelic", methods=["POST"], view_func=rlv2.rlv2ChooseInitialRelic)
app.add_url_rule("/rlv2/selectChoice", methods=["POST"], view_func=rlv2.rlv2SelectChoice)
app.add_url_rule("/rlv2/chooseInitialRecruitSet", methods=["POST"], view_func=rlv2.rlv2ChooseInitialRecruitSet)
app.add_url_rule("/rlv2/activeRecruitTicket", methods=["POST"], view_func=rlv2.rlv2ActiveRecruitTicket)
app.add_url_rule("/rlv2/recruitChar", methods=["POST"], view_func=rlv2.rlv2RecruitChar)
app.add_url_rule("/rlv2/closeRecruitTicket", methods=["POST"], view_func=rlv2.rlv2CloseRecruitTicket)
app.add_url_rule("/rlv2/finishEvent", methods=["POST"], view_func=rlv2.rlv2FinishEvent)
app.add_url_rule("/rlv2/moveAndBattleStart", methods=["POST"], view_func=rlv2.rlv2MoveAndBattleStart)
app.add_url_rule("/rlv2/battleFinish", methods=["POST"], view_func=rlv2.rlv2BattleFinish)
app.add_url_rule("/rlv2/finishBattleReward", methods=["POST"], view_func=rlv2.rlv2FinishBattleReward)
app.add_url_rule("/rlv2/moveTo", methods=["POST"], view_func=rlv2.rlv2MoveTo)
app.add_url_rule("/rlv2/buyGoods", methods=["POST"], view_func=rlv2.rlv2BuyGoods)
app.add_url_rule("/rlv2/leaveShop", methods=["POST"], view_func=rlv2.rlv2LeaveShop)
app.add_url_rule("/rlv2/chooseBattleReward", methods=["POST"], view_func=rlv2.rlv2ChooseBattleReward)
app.add_url_rule("/rlv2/shopAction", methods=["POST"], view_func=rlv2.rlv2shopAction)
app.add_url_rule("/rlv2/copper/confirmDraw", methods=["POST"], view_func=rlv2.rlv2CopperConfirmDraw)
app.add_url_rule("/rlv2/copper/redraw", methods=["POST"], view_func=rlv2.rlv2CopperRedraw)
app.add_url_rule("/rlv2/bankPut", methods=["POST"], view_func=rlv2.rlv2BankPut)
app.add_url_rule("/rlv2/bankWithdraw", methods=["POST"], view_func=rlv2.rlv2BankWithdraw)
app.add_url_rule("/rlv2/nodeMission/confirm", methods=["POST"], view_func=rlv2.rlv2NodeMissionConfirm)
app.add_url_rule("/rlv2/nodeMission/giveUp", methods=["POST"], view_func=rlv2.rlv2NodeMissionGiveUp)
app.add_url_rule("/rlv2/nodeMission/closeTip", methods=["POST"], view_func=rlv2.rlv2NodeMissionCloseTip)
app.add_url_rule("/rlv2/readEndingChange", methods=["POST"], view_func=rlv2.rlv2ReadEndingChange)
app.add_url_rule("/rlv2/rerollNode", methods=["POST"], view_func=rlv2.rlv2RerollNode)
app.add_url_rule("/rlv2/upgradeNode", methods=["POST"], view_func=rlv2.rlv2UpgradeNode)
app.add_url_rule("/rlv2/getTicketAssistList", methods=["POST"], view_func=rlv2.rlv2GetTicketAssistList)
app.add_url_rule("/rlv2/recruitAssistChar", methods=["POST"], view_func=rlv2.rlv2RecruitAssistChar)
app.add_url_rule("/rlv2/diceChoice", methods=["POST"], view_func=rlv2.rlv2DiceChoice)
app.add_url_rule("/rlv2/sacrificeChoice", methods=["POST"], view_func=rlv2.rlv2SacrificeChoice)
app.add_url_rule("/rlv2/copper/gild", methods=["POST"], view_func=rlv2.rlv2CopperGild)
app.add_url_rule("/rlv2/expeditionChoice", methods=["POST"], view_func=rlv2.rlv2ExpeditionChoice)
app.add_url_rule("/rlv2/game/confirmExpeditonReturn", methods=["POST"], view_func=rlv2.rlv2ConfirmExpeditonReturn)
app.add_url_rule("/rlv2/shopBattleStart", methods=["POST"], view_func=rlv2.rlv2ShopBattleStart)
app.add_url_rule("/rlv2/refreshShop", methods=["POST"], view_func=rlv2.rlv2RefreshShop)
app.add_url_rule("/rlv2/setPinned", methods=["POST"], view_func=rlv2.rlv2SetPinned)
app.add_url_rule("/rlv2/confirmZoneReward", methods=["POST"], view_func=rlv2.rlv2ConfirmZoneReward)
app.add_url_rule("/rlv2/confirmTraderReturn", methods=["POST"], view_func=rlv2.rlv2ConfirmTraderReturn)
app.add_url_rule("/rlv2/useStashedTicket", methods=["POST"], view_func=rlv2.rlv2UseStashedTicket)
app.add_url_rule("/rlv2/stashRecruitTicket", methods=["POST"], view_func=rlv2.rlv2StashRecruitTicket)
app.add_url_rule("/rlv2/specialZone/leave", methods=["POST"], view_func=rlv2.rlv2SpecialZoneLeave)
app.add_url_rule("/rlv2/chooseInitialExploreTool", methods=["POST"], view_func=rlv2.rlv2ChooseInitialExploreTool)
app.add_url_rule("/rlv2/battlePass/getReward", methods=["POST"], view_func=rlv2.rlv2getReward)

app.add_url_rule("/shop/getGoodPurchaseState", methods=["POST"], view_func=shop.getGoodPurchaseState)
app.add_url_rule("/shop/get<string:shop_type>GoodList", methods=["POST"], view_func=shop.getShopGoodList)
app.add_url_rule("/shop/buy<string:shop_type>Good", methods=["POST"], view_func=shop.buyShopGood)
app.add_url_rule("/shop/buy<string:shop_type>GoodWithTicket", methods=["POST"], view_func=shop.buyShopGoodWithTicket)
app.add_url_rule("/shop/decomposePotentialItem", methods=["POST"], view_func=shop.decomposePotentialItem)
app.add_url_rule("/shop/decomposeClassicPotentialItem", methods=["POST"], view_func=shop.decomposeClassicPotentialItem)
app.add_url_rule("/shop/getCashGoodPurchaseResult", methods=["POST"], view_func=shop.getCashGoodPurchaseResult)
app.add_url_rule("/shop/getVoucherSkinGoodList", methods=["POST"], view_func=shop.getVoucherSkinGoodList)
app.add_url_rule("/shop/useVoucherSkin", methods=["POST"], view_func=shop.useVoucherSkin)
app.add_url_rule("/shop/checkForbidden", methods=["POST"], view_func=shop.checkForbidden)

app.add_url_rule('/depot/getVoucherDetail', methods=['POST'], view_func=depot.getVoucherDetail)
app.add_url_rule("/depot/voucherGacha", methods=["POST"], view_func=depot.voucherGacha)
app.add_url_rule("/depot/getCharGachaVoucherDetail", methods=["POST"], view_func=depot.getCharGachaVoucherDetail)
app.add_url_rule("/depot/getMaterialVoucherDetail", methods=["POST"], view_func=depot.getMaterialVoucherDetail)
app.add_url_rule("/depot/useCharGachaVoucher", methods=["POST"], view_func=depot.useCharGachaVoucher)
app.add_url_rule("/depot/useMaterialVoucher", methods=["POST"], view_func=depot.useMaterialVoucher)
app.add_url_rule("/depot/useFullPotentialItem", methods=["POST"], view_func=depot.useFullPotentialItem)
app.add_url_rule("/depot/useOptionVoucher", methods=["POST"], view_func=depot.useOptionVoucher)

app.add_url_rule("/templateShop/getGoodList", methods=["POST"], view_func=templateShop.getGoodList)
app.add_url_rule("/templateShop/BuyGood", methods=["POST"], view_func=templateShop.buyGood)

app.add_url_rule("/story/finishStory", methods=["POST"], view_func=story.storyFinishStory)
app.add_url_rule("/quest/finishStoryStage", methods=["POST"], view_func=story.storyFinishStory)

app.add_url_rule("/mainlineClue/unlockClue", methods=["POST"], view_func=user.mainlineClue.unlockClue)
app.add_url_rule("/cg/getCgCollection", methods=["POST"], view_func=user.CG.getCgCollection)
app.add_url_rule("/cg/addCgCollection", methods=["POST"], view_func=user.CG.addCgCollection)
app.add_url_rule("/cg/removeCgCollection", methods=["POST"], view_func=user.CG.removeCgCollection)
app.add_url_rule("/gallery/getFirstRewards", methods=["POST"], view_func=user.gallery.getFirstRewards)
app.add_url_rule("/gallery/getThumbnailUrl", methods=["POST"], view_func=user.gallery.galleryGetThumbnailUrl)
app.add_url_rule("/gallery/changeMagazineSquad", methods=["POST"], view_func=user.gallery.changeMagazineSquad)
app.add_url_rule("/gallery/saveDiyMagazineV1", methods=["POST"], view_func=user.gallery.saveDiyMagazineV1)
app.add_url_rule("/gallery/jpg/<string:jpg_name>", methods=["GET"], view_func=user.gallery.getJpg)
app.add_url_rule("/gallery/getCollectionRewards", methods=["POST"], view_func=user.gallery.getCollectionRewards)
app.add_url_rule("/businessCard/getOtherPlayerNameCard", methods=["POST"], view_func=user.getOtherPlayerNameCard)
app.add_url_rule("/businessCard/editNameCard", methods=["POST"], view_func=user.editNameCard)
app.add_url_rule("/user/bindBirthday", methods=["POST"], view_func=user.bindBirthday)
app.add_url_rule("/general/v1/send_phone_code", methods=["POST"], view_func=user.send_phone_code)
app.add_url_rule("/user/auth", methods=["POST"], view_func=user.auth)
app.add_url_rule("/user/agreement", methods=["GET"], view_func=user.agreement)
app.add_url_rule("/user/checkIn", methods=["POST"], view_func=user.checkin.userCheckIn)
app.add_url_rule("/user/changeSecretary", methods=["POST"], view_func=user.changeSecretary)
app.add_url_rule("/user/login", methods=["POST"], view_func=user.login)
app.add_url_rule("/user/changeAvatar", methods=["POST"], view_func=user.changeAvatar)
app.add_url_rule("/user/oauth2/v1/grant", methods=["POST"], view_func=user.OAuth2V1Grant)
app.add_url_rule("/user/info/v1/need_cloud_auth", methods=["POST"], view_func=user.V1NeedCloudAuth)
app.add_url_rule("/user/yostar_createlogin", methods=["POST"], view_func=user.YostarCreatelogin)
app.add_url_rule("/u8/user/v1/getToken", methods=["POST"], view_func=user.V1getToken)
app.add_url_rule("/user/changeResume", methods=["POST"], view_func=user.changeResume)
app.add_url_rule("/businessCard/changeNameCardComponent", methods=["POST"], view_func=user.businessCard_changeNameCardComponent)
app.add_url_rule("/businessCard/changeNameCardSkin", methods=["POST"], view_func=user.businessCard_changeNameCardSkin)
app.add_url_rule("/user/auth/v1/token_by_phone_password", methods=["POST"], view_func=user.token_by_phone_password)
app.add_url_rule("/user/auth/v2/token_by_phone_code", methods=["POST"], view_func=user.token_by_phone_code)
app.add_url_rule("/user/info/v1/basic", methods=["GET"], view_func=user.info_v1_basic)
app.add_url_rule("/user/oauth2/v2/grant", methods=["POST"], view_func=user.oauth2_v2_grant)
app.add_url_rule("/app/v1/config", methods=["GET"], view_func=user.app_v1_config)
app.add_url_rule("/u8/user/auth/v1/agreement_version", methods=["GET"], view_func=user.agreement_version)
app.add_url_rule("/general/v1/server_time", methods=["GET"], view_func=user.server_time)
app.add_url_rule("/user/exchangeDiamondShard", methods=["POST"], view_func=user.exchangeDiamondShard)
app.add_url_rule("/user/useRenameCard", methods=["POST"], view_func=user.useRenameCard)
app.add_url_rule("/user/bindNickName", methods=["POST"], view_func=user.bindNickName)
app.add_url_rule("/user/changePassword", methods=["POST"], view_func=user.changePassword)
app.add_url_rule("/user/changePhoneCheck", methods=["POST"], view_func=user.changePhoneCheck)
app.add_url_rule("/user/changePhone", methods=["POST"], view_func=user.changePhone)
app.add_url_rule("/user/sendSmsCode", methods=["POST"], view_func=user.sendSmsCode)
app.add_url_rule("/user/register", methods=["POST"], view_func=user.register)
app.add_url_rule("/user/authenticateUserIdentity", methods=["POST"], view_func=user.authenticateUserIdentity)
app.add_url_rule("/user/checkIdCard", methods=["POST"], view_func=user.checkIdCard)
app.add_url_rule("/user/updateAgreement", methods=["POST"], view_func=user.updateAgreement)
app.add_url_rule("/user/v1/guestLogin", methods=["POST"], view_func=user.guestLogin)
app.add_url_rule("/user/loginBySmsCode", methods=["POST"], view_func=user.loginBySmsCode)
app.add_url_rule("/user/buyAp", methods=["POST"], view_func=user.buyAp)
app.add_url_rule("/user/useItem", methods=["POST"], view_func=user.useItem)
app.add_url_rule("/user/useItems", methods=["POST"], view_func=user.useItems)
app.add_url_rule("/user/receiveTeamCollectionReward", methods=["POST"], view_func=user.receiveTeamCollectionReward)
app.add_url_rule("/medal/rewardMedal", methods=["POST"], view_func=user.medal_rewardMedal)

app.add_url_rule("/sandboxPerm/changeTopic", methods=["POST"], view_func=sandbox.changeTopic)
app.add_url_rule("/sandboxPerm/pinTopic", methods=["POST"], view_func=sandbox.pinTopic)
app.add_url_rule("/sandboxPerm/sandboxV2/alchemy", methods=["POST"], view_func=sandbox.sandboxV2.alchemy)
app.add_url_rule("/sandboxPerm/sandboxV2/baseUpgrade", methods=["POST"], view_func=sandbox.sandboxV2.baseUpgrade)
app.add_url_rule("/sandboxPerm/sandboxV2/build", methods=["POST"], view_func=sandbox.sandboxV2.build)
app.add_url_rule("/sandboxPerm/sandboxV2/cook", methods=["POST"], view_func=sandbox.sandboxV2.cook)
app.add_url_rule("/sandboxPerm/sandboxV2/discardAp", methods=["POST"], view_func=sandbox.sandboxV2.discardAp)
app.add_url_rule("/sandboxPerm/sandboxV2/enterChallenge", methods=["POST"], view_func=sandbox.sandboxV2.enterChallenge)
app.add_url_rule("/sandboxPerm/sandboxV2/exitChallenge", methods=["POST"], view_func=sandbox.sandboxV2.exitChallenge)
app.add_url_rule("/sandboxPerm/sandboxV2/extract", methods=["POST"], view_func=sandbox.sandboxV2.extract)
app.add_url_rule("/sandboxPerm/sandboxV2/getChallengeReward", methods=["POST"], view_func=sandbox.sandboxV2.getChallengeReward)
app.add_url_rule("/sandboxPerm/sandboxV2/guideLoad", methods=["POST"], view_func=sandbox.sandboxV2.guideLoad)
app.add_url_rule("/sandboxPerm/sandboxV2/load", methods=["POST"], view_func=sandbox.sandboxV2.load)
app.add_url_rule("/sandboxPerm/sandboxV2/nextDay", methods=["POST"], view_func=sandbox.sandboxV2.V2nextDay)
app.add_url_rule("/sandboxPerm/sandboxV2/racing/battleFinish", methods=["POST"], view_func=sandbox.sandboxV2.racingBattleFinish)
app.add_url_rule("/sandboxPerm/sandboxV2/racing/battleStart", methods=["POST"], view_func=sandbox.sandboxV2.racingBattleStart)
app.add_url_rule("/sandboxPerm/sandboxV2/racing/learnTalent", methods=["POST"], view_func=sandbox.sandboxV2.racingLearnTalent)
app.add_url_rule("/sandboxPerm/sandboxV2/racing/register", methods=["POST"], view_func=sandbox.sandboxV2.racingRegister)
app.add_url_rule("/sandboxPerm/sandboxV2/racing/release", methods=["POST"], view_func=sandbox.sandboxV2.racingRelease)
app.add_url_rule("/sandboxPerm/sandboxV2/racing/saveMark", methods=["POST"], view_func=sandbox.sandboxV2.racingSaveMark)
app.add_url_rule("/sandboxPerm/sandboxV2/removeSupply", methods=["POST"], view_func=sandbox.sandboxV2.removeSupply)
app.add_url_rule("/sandboxPerm/sandboxV2/riftClose", methods=["POST"], view_func=sandbox.sandboxV2.riftClose)
app.add_url_rule("/sandboxPerm/sandboxV2/riftCreate", methods=["POST"], view_func=sandbox.sandboxV2.riftCreate)
app.add_url_rule("/sandboxPerm/sandboxV2/riftSetDifficulty", methods=["POST"], view_func=sandbox.sandboxV2.riftSetDifficulty)
app.add_url_rule("/sandboxPerm/sandboxV2/riftSetTeam", methods=["POST"], view_func=sandbox.sandboxV2.riftSetTeam)
app.add_url_rule("/sandboxPerm/sandboxV2/riftSettle", methods=["POST"], view_func=sandbox.sandboxV2.riftSettle)
app.add_url_rule("/sandboxPerm/sandboxV2/setSupply", methods=["POST"], view_func=sandbox.sandboxV2.setSupply)
app.add_url_rule("/sandboxPerm/sandboxV2/settleChallenge", methods=["POST"], view_func=sandbox.sandboxV2.settleChallenge)
app.add_url_rule("/sandboxPerm/sandboxV2/settleDay", methods=["POST"], view_func=sandbox.sandboxV2.settleDay)
app.add_url_rule("/sandboxPerm/sandboxV2/shopBuy", methods=["POST"], view_func=sandbox.sandboxV2.V2shopBuy)
app.add_url_rule("/sandboxPerm/sandboxV2/startMission", methods=["POST"], view_func=sandbox.sandboxV2.startMission)
app.add_url_rule("/sandboxPerm/sandboxV2/switchMode", methods=["POST"], view_func=sandbox.sandboxV2.V2switchMode)
app.add_url_rule("/sandboxPerm/sandboxV2/unlockTech", methods=["POST"], view_func=sandbox.sandboxV2.V2unlockTech)
app.add_url_rule("/sandboxPerm/sandboxV2/createGame", methods=["POST"], view_func=sandbox.sandboxV2.V2createGame)
app.add_url_rule("/sandboxPerm/sandboxV2/battleStart", methods=["POST"], view_func=sandbox.sandboxV2.V2battleStart)
app.add_url_rule("/sandboxPerm/sandboxV2/battleFinish", methods=["POST"], view_func=sandbox.sandboxV2.V2battleFinish)
app.add_url_rule("/sandboxPerm/sandboxV2/setSquad", methods=["POST"], view_func=sandbox.sandboxV2.setSquad)
app.add_url_rule("/sandboxPerm/sandboxV2/homeBuildSave", methods=["POST"], view_func=sandbox.sandboxV2.homeBuildSave)
app.add_url_rule("/sandboxPerm/sandboxV2/settleGame", methods=["POST"], view_func=sandbox.sandboxV2.V2settleGame)
app.add_url_rule("/sandboxPerm/sandboxV2/eatFood", methods=["POST"], view_func=sandbox.sandboxV2.V2eatFood)
app.add_url_rule("/sandboxPerm/sandboxV2/exploreMode", methods=["POST"], view_func=sandbox.sandboxV2.exploreMode)
app.add_url_rule("/sandboxPerm/sandboxV2/eventChoice", methods=["POST"], view_func=sandbox.sandboxV2.V2eventChoice)
app.add_url_rule("/sandboxPerm/sandboxV2/monthBattleStart", methods=["POST"], view_func=sandbox.sandboxV2.monthBattleStart)
app.add_url_rule("/sandboxPerm/sandboxV2/monthBattleFinish", methods=["POST"], view_func=sandbox.sandboxV2.monthBattleFinish)
app.add_url_rule("/sandboxPerm/sandboxV2/cookDrink", methods=["POST"], view_func=sandbox.sandboxV2.cookDrink)
app.add_url_rule("/sandboxPerm/sandboxV2/cookFood", methods=["POST"], view_func=sandbox.sandboxV2.cookFood)
app.add_url_rule("/sandboxPerm/sandboxV3/switchMode", methods=["POST"], view_func=sandbox.sandboxV3.V3switchMode)
app.add_url_rule("/sandboxPerm/sandboxV3/productionRefresh", methods=["POST"], view_func=sandbox.sandboxV3.productionRefresh)
app.add_url_rule("/sandboxPerm/sandboxV3/productionHarvest", methods=["POST"], view_func=sandbox.sandboxV3.productionHarvest)
app.add_url_rule("/sandboxPerm/sandboxV3/homeEnter", methods=["POST"], view_func=sandbox.sandboxV3.homeEnter)
app.add_url_rule("/sandboxPerm/sandboxV3/homeShopBuy", methods=["POST"], view_func=sandbox.sandboxV3.homeShopBuy)
app.add_url_rule("/sandboxPerm/sandboxV3/homeShopSell", methods=["POST"], view_func=sandbox.sandboxV3.homeShopSell)
app.add_url_rule("/sandboxPerm/sandboxV3/homeUpgrade", methods=["POST"], view_func=sandbox.sandboxV3.homeUpgrade)
app.add_url_rule("/sandboxPerm/sandboxV3/homeSave", methods=["POST"], view_func=sandbox.sandboxV3.homeSave)
app.add_url_rule("/sandboxPerm/sandboxV3/createGame", methods=["POST"], view_func=sandbox.sandboxV3.V3createGame)
app.add_url_rule("/sandboxPerm/sandboxV3/giveUpGame", methods=["POST"], view_func=sandbox.sandboxV3.V3giveUpGame)
app.add_url_rule("/sandboxPerm/sandboxV3/battleStart", methods=["POST"], view_func=sandbox.sandboxV3.V3battleStart)
app.add_url_rule("/sandboxPerm/sandboxV3/battleFinish", methods=["POST"], view_func=sandbox.sandboxV3.V3battleFinish)
app.add_url_rule("/sandboxPerm/sandboxV3/changeDefend", methods=["POST"], view_func=sandbox.sandboxV3.changeDefend)
app.add_url_rule("/sandboxPerm/sandboxV3/chooseBand", methods=["POST"], view_func=sandbox.sandboxV3.chooseBand)
app.add_url_rule("/sandboxPerm/sandboxV3/dailyRecruit", methods=["POST"], view_func=sandbox.sandboxV3.dailyRecruit)
app.add_url_rule("/sandboxPerm/sandboxV3/eatFood", methods=["POST"], view_func=sandbox.sandboxV3.V3eatFood)
app.add_url_rule("/sandboxPerm/sandboxV3/eventChoice", methods=["POST"], view_func=sandbox.sandboxV3.V3eventChoice)
app.add_url_rule("/sandboxPerm/sandboxV3/getDailyRecruitList", methods=["POST"], view_func=sandbox.sandboxV3.getDailyRecruitList)
app.add_url_rule("/sandboxPerm/sandboxV3/nextDay", methods=["POST"], view_func=sandbox.sandboxV3.V3nextDay)
app.add_url_rule("/sandboxPerm/sandboxV3/initRecruit", methods=["POST"], view_func=sandbox.sandboxV3.initRecruit)
app.add_url_rule("/sandboxPerm/sandboxV3/settleGame", methods=["POST"], view_func=sandbox.sandboxV3.V3settleGame)
app.add_url_rule("/sandboxPerm/sandboxV3/shopBuy", methods=["POST"], view_func=sandbox.sandboxV3.V3shopBuy)
app.add_url_rule("/sandboxPerm/sandboxV3/shopBuyRecruit", methods=["POST"], view_func=sandbox.sandboxV3.shopBuyRecruit)
app.add_url_rule("/sandboxPerm/sandboxV3/shopRefresh", methods=["POST"], view_func=sandbox.sandboxV3.shopRefresh)
app.add_url_rule("/sandboxPerm/sandboxV3/shopSell", methods=["POST"], view_func=sandbox.sandboxV3.shopSell)
app.add_url_rule("/sandboxPerm/sandboxV3/unlockTech", methods=["POST"], view_func=sandbox.sandboxV3.V3unlockTech)

app.add_url_rule("/gacha/normalGacha", methods=["POST"], view_func=gacha.normalGacha)
app.add_url_rule("/gacha/boostNormalGacha", methods=["POST"], view_func=gacha.boostNormalGacha)
app.add_url_rule("/gacha/finishNormalGacha", methods=["POST"], view_func=gacha.finishNormalGacha)
app.add_url_rule("/gacha/syncNormalGacha", methods=["POST"], view_func=gacha.syncNormalGacha)
app.add_url_rule("/gacha/getPoolDetail", methods=["POST"], view_func=gacha.getPoolDetail)
app.add_url_rule("/gacha/advancedGacha", methods=["POST"], view_func=gacha.advancedGacha)
app.add_url_rule("/gacha/tenAdvancedGacha", methods=["POST"], view_func=gacha.tenAdvancedGacha)
app.add_url_rule("/gacha/choosePoolUp", methods=["POST"], view_func=gacha.choosePoolUp)
app.add_url_rule("/gacha", methods = ["GET"], view_func=gacha.gacha)
app.add_url_rule("/api/gacha/cate", methods = ["GET"], view_func=gacha.cate)
app.add_url_rule("/api/is/rogue_1/bulletinVersion", methods = ["GET"], view_func=gacha.bulletinVersion)
app.add_url_rule("/api/gacha/history", methods = ["GET"], view_func=gacha.history)
app.add_url_rule("/gacha/cancelNormalGacha", methods=["POST"], view_func=gacha.cancelNormalGacha)
app.add_url_rule("/gacha/buyRecruitSlot", methods=["POST"], view_func=gacha.buyRecruitSlot)
app.add_url_rule("/gacha/getFreeChar", methods=["POST"], view_func=gacha.getFreeChar)

app.add_url_rule('/social/setAssistCharList', methods=['POST'], view_func=social.setAssistCharList)
app.add_url_rule('/social/getSortListInfo', methods=['POST'], view_func=social.getSortListInfo)
app.add_url_rule('/social/getFriendList', methods=['POST'], view_func=social.getFriendList)
app.add_url_rule('/social/getFriendRequestList', methods=['POST'], view_func=social.getFriendRequestList)
app.add_url_rule('/social/processFriendRequest', methods=['POST'], view_func=social.processFriendRequest)
app.add_url_rule('/social/sendFriendRequest', methods=['POST'], view_func=social.sendFriendRequest)
app.add_url_rule('/social/setFriendAlias', methods=['POST'], view_func=social.setFriendAlias)
app.add_url_rule('/social/deleteFriend', methods=['POST'], view_func=social.deleteFriend)
app.add_url_rule('/social/searchPlayer', methods=['POST'], view_func=social.searchPlayer)
app.add_url_rule("/social/setCardShowMedal", methods=["POST"], view_func=social.setCardShowMedal)
app.add_url_rule("/social/receiveSocialPoint", methods=["POST"], view_func=social.receiveSocialPoint)
app.add_url_rule("/social/setStarFriendList", methods=["POST"], view_func=social.setStarFriendList)

# app.add_url_rule("/iedsafe/Client/android/19791/config2.xml", methods = ["GET"], view_func=other.anticheat)
# app.add_url_rule("/event", methods=["POST"], view_func=other.event)
# app.add_url_rule("/batch_event", methods=["POST"], view_func=other.batch_event)
# app.add_url_rule("/beat", methods=["POST"], view_func=other.beat)
# app.add_url_rule("/deviceprofile/v4", methods=["POST"], view_func=other.deviceprofile)
# app.add_url_rule("/loggw/logUpload.do", methods=["POST"], view_func=other.logUploaddo)
# app.add_url_rule("/mgw.htm", methods=["POST"], view_func=other.mgw)
# app.add_url_rule("/admin/cheat", methods=["POST"], view_func=other.cheat)
# app.add_url_rule("/admin/getVersion", methods=["POST"], view_func=other.getVersion)
# app.add_url_rule("/survey/startSurvey", methods=["POST"], view_func=other.startSurvey)
app.add_url_rule("/npcAudio/changeLan", methods=["POST"], view_func=other.npcAudioChangeLan)

app.add_url_rule("/charRotation/setCurrent", methods=["POST"], view_func=charrotation.setCurrent)
app.add_url_rule("/charRotation/createPreset", methods=["POST"], view_func=charrotation.createPreset)
app.add_url_rule("/charRotation/deletePreset", methods=["POST"], view_func=charrotation.deletePreset)
app.add_url_rule("/charRotation/updatePreset", methods=["POST"], view_func=charrotation.updatePreset)

app.add_url_rule('/recalRune/battleStart', methods=['POST'], view_func=crisis.recalRune_battleStart)
app.add_url_rule('/recalRune/battleFinish', methods=['POST'], view_func=crisis.recalRune_battleFinish)
app.add_url_rule("/crisis/getGoodList", methods=["POST"], view_func=crisis.crisisgetGoodList)
app.add_url_rule("/crisis/buyGoods", methods=["POST"], view_func=crisis.buyGoods)
app.add_url_rule("/crisis/challengeRewardTask", methods=["POST"], view_func=crisis.challengeRewardTask)
app.add_url_rule("/crisis/challengeRewardPoint", methods=["POST"], view_func=crisis.challengeRewardPoint)
app.add_url_rule("/crisis/challengeRewardAll", methods=["POST"], view_func=crisis.challengeRewardAll)
app.add_url_rule("/crisis/unlockMapRank", methods=["POST"], view_func=crisis.unlockMapRank)
app.add_url_rule("/crisis/unlockRune", methods=["POST"], view_func=crisis.unlockRune)
app.add_url_rule("/crisis/getAllItems", methods=["POST"], view_func=crisis.getAllItems)
app.add_url_rule("/crisisV2/buyGood", methods=["POST"], view_func=crisis.crisisV2BuyGood)


# 以下为远程管理路由，如果你不打算使用我的管理app，请不要抄过去
app.add_url_rule("/admin/verify", methods=["GET","POST"], view_func=admin.adminVerify)
app.add_url_rule("/admin/saveUserData", methods=["POST"], view_func=admin.adminSaveUserData)
app.add_url_rule("/admin/login/by_phone_password", methods=["POST"], view_func=admin.by_phone_password)

if __name__ == "__main__":
    print(Fore.YELLOW + \
    "──────────────────────────\n" + \
    "该软件开源免费\n" + \
    "如果你花钱了，说明你被骗了\n" + \
    "──────────────────────────"
    )
    writeLog("[SERVER] 加载config.json")
    load_config()
    writeLog("[SERVER] 加载普通数据")
    load_data()
    server_config = get_memory("config")
    host = server_config["server"]["host"]
    port = server_config["server"]["port"]
    useMemoryCache = server_config["server"]["useMemoryCache"]
    if useMemoryCache:
        writeLog("[SERVER] 加载全部table数据到内存中")
        preload_json_data()
    writeLog("[SERVER] 启动协程")
    start_global_event_loop()
    writeLog("[SERVER] 预处理数据")
    character_star_calculate()
    load_admin_key()
    writeLog('[SERVER] 服务器启动于 http://' + host + ":" + str(port))
    app.run(host=host, port=port, debug=True, threaded=True)
